'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider, Button } from "@material-tailwind/react";
import { SessionProvider } from 'next-auth/react';
import { usePathname } from 'next/navigation';
import { checkIsPublicRoute } from '@/functions';

const inter = Inter({ subsets: ['latin'] })

/*export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  const isPublicPage = checkIsPublicRoute(pathname!);

  // se o usuario estiver autenticado e acessar uma rota privada
  //ele conseguir visualizar a pagina!

  // se o usuario nao estivert autenticado e acessar uma rota privada
  //ele nao deve conseguir visualizar a pagina!
  //{isPublicPage && children }
  //{!isPublicPage && <PrivateRoute>{children}</PrivateRoute> }

  console.log(isPublicPage)
  return (
    <html lang="en">
      <body className={inter.className}>
        
      {children}
      </body>
    </html>
  )
}
